<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shared.SharedKernel\Shared.SharedKernel.csproj" />

    <!-- Все версии берутся из Directory.Packages.props -->
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Mazeland.Core</PackageId>
    <Version>1.0.1</Version>
    <Description>Core business logic for Mazeland</Description>
    <Authors>maze37</Authors>
    <RepositoryUrl>https://github.com/maze37/Shared</RepositoryUrl>
    <PackageTags>core domain logic</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
