<Project Sdk="Microsoft.NET.Sdk">
  
    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Npgsql" />
      <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared.SharedKernel\Shared.SharedKernel.csproj" />
    </ItemGroup>

</Project>
