<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" />
      <PackageReference Include="FluentValidation" />
      <PackageReference Include="Npgsql" />
      <PackageReference Include="Scrutor" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared.SharedKernel\Shared.SharedKernel.csproj" />
    </ItemGroup>

</Project>
