<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
        <PackageReference Include="Serilog" />
        <PackageReference Include="Serilog.Exceptions" />
        <PackageReference Include="Serilog.Extensions.Hosting" />
        <PackageReference Include="Serilog.Settings.Configuration" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.File" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared.SharedKernel\Shared.SharedKernel.csproj" />
    </ItemGroup>

  <PropertyGroup>
    <PackageId>Mazeland.Framework</PackageId>
    <Version>2.0.0</Version>
    <Description>Framework layer for Mazeland</Description>
    <Authors>maze37</Authors>
    <RepositoryUrl>https://github.com/maze37/Shared</RepositoryUrl>
    <PackageTags>framework infrastructure</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
