name: Publish Mazeland.SharedKernel

on:
  push:
    tags:
      - 'v*' # Запуск только когда ты создаешь тег версии, например v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    
    # Даем права GitHub Actions на запись пакетов в твой репозиторий
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build Solution
        run: dotnet build -c Release

      - name: Pack SharedKernel
        run: dotnet pack Shared.SharedKernel/Shared.SharedKernel.csproj -c Release --output ./nupkgs

      - name: Push to GitHub Packages
        run: >
          dotnet nuget push ./nupkgs/*.nupkg 
          --source "https://github.com" 
          --api-key "${{ secrets.GITHUB_TOKEN }}" 
          --skip-duplicate
